# Generated by Django 2.2.6 on 2019-10-30 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='prof_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
