# Generated by Django 2.2.6 on 2019-10-30 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_student_prof_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='prof_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
