# Generated by Django 2.2.6 on 2019-10-30 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_teacher_prof_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='prof_image',
            field=models.ImageField(blank=True, upload_to='images/', width_field=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='prof_image',
            field=models.ImageField(blank=True, upload_to='images/', width_field=20),
        ),
    ]
