# Generated by Django 2.2.6 on 2019-10-30 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20191030_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='prof_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='prof_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
