# Generated by Django 2.2.6 on 2019-10-30 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_auto_20191030_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='prof_image',
            field=models.ImageField(blank=True, upload_to='images/', width_field='120px'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='prof_image',
            field=models.ImageField(blank=True, upload_to='images/', width_field='120px'),
        ),
    ]
