# Generated by Django 2.2.6 on 2019-10-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_auto_20191030_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, default='100', editable=False, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, default='100', editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='prof_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='prof_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
