# Generated by Django 2.2.6 on 2019-10-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_auto_20191030_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='prof_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
