# Generated by Django 2.2.6 on 2019-10-30 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_auto_20191030_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='prof_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
