# Generated by Django 2.2.6 on 2019-10-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0010_auto_20191030_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='prof_image',
            field=models.ImageField(blank=True, default='null', null=True, upload_to='images/'),
        ),
    ]
