# Generated by Django 2.2.6 on 2019-10-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0011_auto_20191030_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='prof_image',
            field=models.ImageField(blank=True, default='images/anonym.png', upload_to='images/'),
        ),
    ]
