# Generated by Django 2.2.6 on 2019-10-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0012_auto_20191030_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='prof_image',
            field=models.ImageField(blank=True, default='images/anonym.png', upload_to='images/'),
        ),
    ]
