# Generated by Django 2.2.6 on 2019-10-31 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0013_auto_20191030_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, default='150', editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, default='150', editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, default='150', editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, default='150', editable=False, null=True),
        ),
    ]
